name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        mkdir ${{ github.workspace }}/build
        echo ${{ github.workspace }}/build | python rcc.py install rcc

    - name: Zip files (Windows)
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -DestinationPath rcc-win.zip -Path ${{ github.workspace }}/build/*

    - name: Tar files (Linux)
      if: runner.os == 'Linux'
      run: |
        tar -czvf rcc-linux.tar.gz -C ${{ github.workspace }}/build .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os == 'Windows' && 'rcc-win.zip' || 'rcc-linux.tar.gz' }}
        path: ${{ runner.os == 'Windows' && 'rcc-win.zip' || 'rcc-linux.tar.gz' }}
